version: '3.9'

services:

    app:
        build: .
        volumes:
            - .:/app

    nginx:
        build: ./nginx
        volumes:
            - ./nginx/dhparam:/etc/nginx/dhparam
            - ./nginx/certbot/conf/:/etc/nginx/ssl/
            - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
        ports:
            - 80:80
            - 443:443
            - 8000:8000
            
        depends_on:
            - app
    # certbot:
    #     image: certbot/certbot:latest
    #     command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email myworldofficials@gmail.com --agree-tos --no-eff-email -d others.joinmyworld.in
    #     volumes:
    #         - ./nginx/certbot/conf/:/etc/letsencrypt
    #         - ./nginx/certbot/logs/:/var/log/letsencrypt
    #         - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt

    